sudo: required
services:
  - docker

before_install:
  - docker build -t thevivekpandey/docker-react -f Dockerfile.dev .

script:
  - docker run thevivekpandey/docker-react npm run test -- --coverage
